version: 2
updates:
  # Enable version updates for uv
  - package-ecosystem: "uv"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the uv registry for updates every day (weekdays)
    schedule:
      interval: "daily"